apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: es
spec:
  namespaceSelector:
    matchLabels:
      es: ghcr
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: doppler-apps-creds
    target:
      name: ghcr-pull-secret
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "ghcr.io": {
                  "username": "mervinhemaraju",
                  "password": "{{ .pat }}",
                  "auth": "{{ printf "mervinhemaraju:%s" .pat | b64enc }}"
                }
              }
            }
      creationPolicy: Owner
    data:
      - secretKey: pat
        remoteRef:
          key: GH_PACKAGES_TOKEN     