apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flou-api-release
  namespace: flouapi
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  
  chartRef:
    kind: OCIRepository
    name: plagueworks-helm-charts
    namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: flou-api-values
      valuesKey: values-01.yaml