apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: insightface-rest
  namespace: flux-system
spec:
  interval: 10m
  path: ./helm/src/insightface-rest/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-k8
    namespace: flux-system
