apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-azuredevops-secrets
  namespace: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: css-gcp-cockpit-prod
    kind: ClusterSecretStore

  target:
    name: argocd-repo-azuredevops
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: "{{ .reponame }}"
        url: "{{ .url }}"
        type: "{{ .type }}"
        username: "{{ .username }}"
        password: "{{ .password }}"

  dataFrom:
    - extract:
        key: dke-gcp-shared-git-azuredevops-argocd