apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uniface-release
  namespace: face-verification
spec:
  driftDetection:
    mode: enabled
  interval: 5m

  chartRef:
    kind: OCIRepository
    name: plagueworks-helm-charts
    namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: uniface-values
      valuesKey: values-01.yaml
