apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: compreface-kubernetes
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/exadel-inc/compreface-kubernetes
  ref:
    branch: master
