apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github-k8
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/plagueworks-org/k8-apps
  ref:
    branch: main