---
# ClusterSecretStore for Flou Projects
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-flou-creds
  namespace: es
spec:
  provider:
    doppler:
      project: flou
      config: dev
      auth:
        secretRef:
          dopplerToken:
            namespace: default
            name: doppler-token-auth-api
            key: dopplerToken