apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clstr-oke-prod-zeus-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/plagueworks-org/k8-apps
    targetRevision: feature/core-apps-setup
    path: helm/argocd-apps
  destination:
    name: zeus  # use the cluster name from the secret
    namespace: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true