---
# ClusterSecretStore for Cloud OCI Creds Projects
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-cloud-oci-creds
  namespace: es
spec:
  provider:
    doppler:
      project: cloud-oci-creds
      config: prd
      auth:
        secretRef:
          dopplerToken:
            namespace: default
            name: doppler-token-auth-api
            key: dopplerToken
