apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plagueworks-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/plagueworks-org/k8-apps
    targetRevision: feature/core-apps-setup
    path: helm/argocd-apps/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - PruneLast=true