apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: compreface-db-secret
  namespace: face-verification
spec:
  secretStoreRef:
    name: doppler-cloud-oci-creds
    kind: ClusterSecretStore

  target:
    name: compreface-db-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: DATABASE_USER_COMPREFACE_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
