apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: compreface
  namespace: face-verification
spec:
  driftDetection:
    mode: enabled
  interval: 5m

  chart:
    spec:
      chart: helm-config
      sourceRef:
        kind: GitRepository
        name: compreface-kubernetes
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: compreface-values
      valuesKey: values.yaml

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: cf-db
            patch: |-
              $patch: delete
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cf-db
          - target:
              kind: Service
              name: compreface-postgres-db
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Service
              metadata:
                name: compreface-postgres-db
          - target:
              kind: PersistentVolumeClaim
              name: cf-db-data
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: cf-db-data
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cf-api
              spec:
                template:
                  spec:
                    containers:
                    - name: cf-api
                      env:
                      - name: POSTGRES_PASSWORD
                        value: null
                        valueFrom:
                          secretKeyRef:
                            name: compreface-db-secret
                            key: POSTGRES_PASSWORD
                      - name: POSTGRES_URL
                        value: jdbc:postgresql://10.18.20.10:5432/compreface
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cf-admin
              spec:
                template:
                  spec:
                    containers:
                    - name: cf-admin
                      env:
                      - name: POSTGRES_PASSWORD
                        value: null
                        valueFrom:
                          secretKeyRef:
                            name: compreface-db-secret
                            key: POSTGRES_PASSWORD
                      - name: POSTGRES_URL
                        value: jdbc:postgresql://10.18.20.10:5432/compreface

